export const API_ERROR_MESSAGES = {
  NO_TOKEN: "No hay token de autenticación. Por favor, inicia sesión.",
  
  UNKNOWN_ERROR: {
    LOGIN: "Error desconocido al intentar iniciar sesión",
    GET_ACCOUNTS: "Error desconocido al obtener las cuentas",
    GET_MINIMAL_ACCOUNTS: "Error desconocido al obtener las cuentas mínimas",
    GET_MOVEMENTS: "Error desconocido al obtener los movimientos",
    GET_ACCOUNT_DETAIL: "Error desconocido al obtener el detalle de la cuenta",
    GET_PRODUCT_BALANCES: "Error desconocido al obtener los saldos de productos",
    GET_LOANS: "Error desconocido al obtener los préstamos",
    GET_PAYMENTS: "Error desconocido al obtener los pagos efectuados",
    GET_INSTALLMENT: "Error desconocido al obtener el detalle de la cuota",
    GET_INVESTMENTS: "Error desconocido al obtener las inversiones",
    GET_COUPONS: "Error desconocido al obtener los cupones",
    GET_FAVORITE_ACCOUNTS: "Error desconocido al obtener las cuentas favoritas",
    GET_INTERNAL_FAVORITE_ACCOUNTS: "Error desconocido al obtener las cuentas favoritas internas",
    GET_SINPE_FAVORITE_ACCOUNTS: "Error desconocido al obtener las cuentas favoritas SINPE",
    GET_FAVORITE_WALLETS: "Error desconocido al obtener las favoritas SINPE Móvil",
    GET_DESTINATION_ACCOUNT: "Error desconocido al obtener la cuenta destino",
    GET_DESTINATION_SINPE_ACCOUNT: "Error desconocido al obtener la cuenta destino SINPE",
    GET_DESTINATION_WALLET: "Error desconocido al obtener el destino SINPE Móvil",
    GET_SINPE_WALLET: "Error desconocido al obtener el SINPE Móvil",
    CREATE_INTERNAL_FAVORITE_ACCOUNT: "Error desconocido al crear la cuenta favorita",
    UPDATE_INTERNAL_FAVORITE_ACCOUNT: "Error desconocido al actualizar la cuenta favorita",
    DELETE_INTERNAL_FAVORITE_ACCOUNT: "Error desconocido al eliminar la cuenta favorita",
    CREATE_SINPE_FAVORITE_ACCOUNT: "Error desconocido al crear la cuenta favorita SINPE",
    UPDATE_SINPE_FAVORITE_ACCOUNT: "Error desconocido al actualizar la cuenta favorita SINPE",
    DELETE_SINPE_FAVORITE_ACCOUNT: "Error desconocido al eliminar la cuenta favorita SINPE",
    CREATE_FAVORITE_WALLET: "Error desconocido al crear la favorita SINPE Móvil",
    UPDATE_FAVORITE_WALLET: "Error desconocido al actualizar la favorita SINPE Móvil",
    DELETE_FAVORITE_WALLET: "Error desconocido al eliminar la favorita SINPE Móvil",
    CREATE_CHALLENGE: "Error desconocido al crear el desafío",
    VALIDATE_CHALLENGE: "Error desconocido al validar el desafío",
    DISABLE_DEVICE: "Error desconocido al deshabilitar el dispositivo",
    SEND_INTERNAL_TRANSFER: "Error desconocido al enviar la transferencia",
    SEND_SINPE_TRANSFER: "Error desconocido al enviar la transferencia SINPE",
    SEND_SINPE_MOVIL_TRANSFER: "Error desconocido al enviar la transferencia SINPE Móvil",
    AFFILIATE_WALLET: "Error desconocido al afiliar el SINPE Móvil",
  },
  
  ERROR: {
    LOGIN: "Error al iniciar sesión",
    GET_ACCOUNTS: "Error al obtener las cuentas",
    GET_MINIMAL_ACCOUNTS: "Error al obtener las cuentas mínimas",
    GET_MOVEMENTS: "Error al obtener los movimientos",
    GET_ACCOUNT_DETAIL: "Error al obtener el detalle de la cuenta",
    GET_PRODUCT_BALANCES: "Error al obtener los saldos de productos",
    GET_LOANS: "Error al obtener los préstamos",
    GET_PAYMENTS: "Error al obtener los pagos efectuados",
    GET_INSTALLMENT: "Error al obtener el detalle de la cuota",
    GET_INVESTMENTS: "Error al obtener las inversiones",
    GET_COUPONS: "Error al obtener los cupones",
    GET_FAVORITE_ACCOUNTS: "Error al obtener las cuentas favoritas",
    GET_INTERNAL_FAVORITE_ACCOUNTS: "Error al obtener las cuentas favoritas internas",
    GET_SINPE_FAVORITE_ACCOUNTS: "Error al obtener las cuentas favoritas SINPE",
    GET_FAVORITE_WALLETS: "Error al obtener las favoritas SINPE Móvil",
    GET_DESTINATION_ACCOUNT: "Error al obtener la cuenta destino",
    GET_DESTINATION_SINPE_ACCOUNT: "Error al obtener la cuenta destino SINPE",
    GET_DESTINATION_WALLET: "Error al obtener el destino SINPE Móvil",
    GET_SINPE_WALLET: "Error al obtener el SINPE Móvil",
    CREATE_INTERNAL_FAVORITE_ACCOUNT: "Error al crear la cuenta favorita",
    UPDATE_INTERNAL_FAVORITE_ACCOUNT: "Error al actualizar la cuenta favorita",
    DELETE_INTERNAL_FAVORITE_ACCOUNT: "Error al eliminar la cuenta favorita",
    CREATE_SINPE_FAVORITE_ACCOUNT: "Error al crear la cuenta favorita SINPE",
    UPDATE_SINPE_FAVORITE_ACCOUNT: "Error al actualizar la cuenta favorita SINPE",
    DELETE_SINPE_FAVORITE_ACCOUNT: "Error al eliminar la cuenta favorita SINPE",
    CREATE_FAVORITE_WALLET: "Error al crear la favorita SINPE Móvil",
    UPDATE_FAVORITE_WALLET: "Error al actualizar la favorita SINPE Móvil",
    DELETE_FAVORITE_WALLET: "Error al eliminar la favorita SINPE Móvil",
    CREATE_CHALLENGE: "Error al crear el desafío",
    VALIDATE_CHALLENGE: "Error al validar el desafío",
    DISABLE_DEVICE: "Error al deshabilitar el dispositivo",
    SEND_INTERNAL_TRANSFER: "Error al enviar la transferencia",
    SEND_SINPE_TRANSFER: "Error al enviar la transferencia SINPE",
    SEND_SINPE_MOVIL_TRANSFER: "Error al enviar la transferencia SINPE Móvil",
    AFFILIATE_WALLET: "Error al afiliar el SINPE Móvil",
  },
  
  SECOND_FACTOR_REQUIRED: "Se requiere una validación de segundo factor para esta operación.",
  
  ACCOUNT_ALREADY_EXISTS: "Ya existe una cuenta favorita con el mismo número de cuenta para este cliente.",
  
  SINPE_ACCOUNT_NOT_FOUND: "No se encontró la cuenta destino SINPE.",
  
  WALLET_NOT_FOUND: "No se encontró el SINPE Móvil especificado.",
  
  WALLET_ALREADY_EXISTS: "Ya existe una favorita SINPE Móvil con el mismo número para este cliente.",
  
  FAVORITE_WALLET_NOT_FOUND: "No se encontró la favorita SINPE Móvil especificada.",
} as const;

